version: '3.8'


networks:
  http_net:
    name: http_net
    external: true


services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: description_generator
    restart: on-failure
    environment:
      - "ES_ENDPOINT=http://elastic:changeme@elastic:9200"
    ports:
      - 8001:8001
    networks:
      - http_net